config/routes.rb
Rails.application.routes.draw do

get 'extra/index'

  devise_for :users
resources :results

   root 'welcome#index'

end

app/models/result.rb
class Result < ActiveRecord::Base

belongs_to :user
validates :sexo, presence: true
validates :meses, presence: true
validates :objetivo, presence: true
validates :grasa, presence: true
validates :nivel, presence: true
validates :ritmo, presence: true
validates :meta, presence: true
validates :menu, presence: true
validates :kilos, presence: true
validates :egrasa, presence: true
validates :edad, presence: true
validates :fmin, presence: true
validates :cestado, presence: true
validates :cnivel, presence: true
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/extra_controller.rb
class ExtraController < ApplicationController
  def index
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

before_action :authenticate_user!

def index
@results = current_user.results.all
end

def show
@result = current_user.results.find(params[:id])
end

def new
@result = Result.new
end

def create
@result = current_user.results.new(results_params)
		if	@result.save
		redirect_to @result

	else render :new
	end
end

def destroy
@result = current_user.results.find(params[:id])
@result.destroy
redirect_to results_path
end

def nil.+ other; other end

def edit
end

def update
@result = Result.find(params[:id])	
	if @result.update(res_params)
		redirect_to @result
	else 
		render :edit
end
end

private

def results_params
params.require(:result).permit(
:sexo,
:meses,
:objetivo,
:grasa,
:nivel,
:ritmo,
:meta,
:menu,
:kilos,
:egrasa,
:edad,
:fmin,
:cestado,
:cnivel,
)
end

def res_params
params.require(:result).permit(	
:c1e, :c1a, :c1g,
:c2e, :c2a, :c2g,
:c3e, :c3a, :c3g,
:c4e, :c4a, :c4g,
:c5e, :c5a, :c5g,
:c6e, :c6a, :c6g,
:c7e, :c7a, :c7g,
:c8e, :c8a, :c8g,
:c9e, :c9a, :c9g,
:c10e, :c10a, :c10g,
:c11e, :c11a, :c11g,
:c12e, :c12a, :c12g,
:c13e, :c13a, :c13g,
:c14e, :c14a, :c14g,
:c15e, :c15a, :c15g,
:c16e, :c16a, :c16g,
:c17e, :c17a, :c17g,
:c18e, :c18a, :c18g,
:c19e, :c19a, :c19g,
:c20e, :c20a, :c20g,
:c21e, :c21a, :c21g,
:c22e, :c22a, :c22g,
:c23e, :c23a, :c23g,
:c24e, :c24a, :c24g,
:c25e, :c25a, :c25g,
:c26e, :c26a, :c26g,
:c27e, :c27a, :c27g,
:c28e, :c28a, :c28g,
:c29e, :c29a, :c29g,
:c30e, :c30a, :c30g,
)
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extra_helper.rb
module ExtraHelper
end

app/views/alimentacion/_menu1.html.erb
<h1>
    Aqui va el resultado de Alimentación
</h1>

app/views/cardio/_cardio1.html.erb
<h1>
    Aqui va el resultado de Cardiovascular
</h1>

app/views/complementos/_comple1a.html.erb
<h1>
    Aqui va el resultado de Complementos
</h1>

app/views/complementos/_descanso.html.erb
<p>Proteína, Glutamina y BCAA´s: Se puede estar tomando estos complementos de forma constante pero es importante seguir manteniendo el entrenamiento<br>
		Creatina: Se recomienda tomarse durante 3 meses y mínimo descansar 1 mes.<br>
		Complejo Multivitamínico: Se recomienda tomarse durante 2 meses y mínimo descansar 1 mes.<br>
		Óxido Nítrico: Se recomienda tomarse durante 3 meses y descansar 2 meses. Tomar antioxidantes ya sea de los propios alimentos o de forma en suplemento para contrarestar la aparición de radicales libres.<br>
		Termogénicos: Principalmente se debe tomar entre 1 mes por 15 días de descanso.<br>
		L-Carnitina: Su descanso es por 1 mes, aunque puede estarse tomando durante 2 meses.<br>
		Tribulus: Se recomienda tomarse durante 3 meses y mínimo descansar 4 mes.<br>
		</p>

app/views/entrenamiento/_zdpn1.html.erb
<h1>
    Aqui va el resultado de Entrenamiento
</h1>

app/views/extra/_antes.html.erb
<h1>
    Aqui van las instrucciones de compra
</h1>

app/views/extra/_fcm.html.erb
<h1>
    Aqui va la tabla de FMAX
</h1>

app/views/extra/_grasa.html.erb
<h1>
    Aqui presentacion de % de grasa
</h1>

app/views/extra/_unorm.html.erb
<h1>
    Aqui va calculo de 1rm
</h1>

app/views/extra/index.html.erb
<div class="resultNav">
	<input type="button" value="Antes de comprar" class="botonR antes">
	<input type="button" value="¿Cuanto peso cargar?" class="botonR 1rm">
	<input type="button" value="Frecuencia cardiaca" class="botonR fcm">
	<input type="button" value="Grasa corporal" class="botonR grasacorp">
</div>
	
	<div class="scrollR">
		<div style="display:none;" id="antes">
		<%=render "antes"%>
		</div>
		<div style="display:none;" id="1rm">
		<%=render "unorm"%>
		</div>
		<div style="display:none;" id="fcm">
		<%=render "fcm"%>
		</div>
		<div style="display:none;" id="grasacorp">
		<%=render "grasa"%>
		</div>	
	</div>

<script type="text/javascript">
	$(document).ready(function(){
    $(".antes").click(function(){
        $("#antes").toggle(1500);
        $("#1rm").hide();
        $("#fcm").hide();
        $("#grasacorp").hide();
    });
});

		$(document).ready(function(){
    $(".1rm").click(function(){
        $("#1rm").toggle(1500);
        $("#antes").hide();
        $("#fcm").hide();
        $("#grasacorp").hide();
    });
});

			$(document).ready(function(){
    $(".fcm").click(function(){
        $("#fcm").toggle(1500);
        $("#1rm").hide();
        $("#antes").hide();
        $("#grasacorp").hide();
    });
});

				$(document).ready(function(){
    $(".grasacorp").click(function(){
        $("#grasacorp").toggle(1500);
        $("#1rm").hide();
        $("#fcm").hide();
        $("#antes").hide();
    });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Winfitt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
</head>
<body>
<%= render "partials/navigation" %>
<%= yield %>
</body>
</html>

app/views/partials/_navigation.html.erb
<div class="logoWinfitt">
<%= link_to root_path do %>
<img style="width:300px;" src="<%= asset_path 'anuncios/super logo.png' %>">
<% end %>	
</div>

<style type="text/css">

header{
display: g;
}

.burguerMenu{
display:none;
}

.logoWinfitt{
position: absolute;
left: 10px;
}

.logoWinfittMovil{
display: none;
}

ul{
list-style: none;
}

.fondo{
background-color: rgba(255, 255, 255, 0.7);
width:100%;
padding: 10px 10px;
}

.nav{
padding: 0;
margin:4px;
font-style: none;
color: #0C0B0C;
}

.pieDePagina{
right: 0;
bottom: 0;
left: 0;
padding: 4px;
text-align: center;
float:left; 
width:20%;
height: 10%;
position:fixed;
}

.facebook{
float: left;
width: 60px;
margin: 2px;
display: inline-block;
}

.botonPaypal{
position: absolute;
right: 20px;
}

		@media (max-width: 500px){
		.burguerMenu{
		position: fixed;
		z-index: 2;
		width: 45px;
		right: 15px;
		top: 15px;
		display: inline-block;
		}


		header{
		position: relative;
		z-index: 1; display: none;
		}

		.logoWinfitt{
		display: none;
		}

		.logoWinfittMovil{
		display: initial;
		}

		ul{
		list-style: none;
		}


		.fondo{
		background-color: rgba(255, 255, 255, 0.8);
		width:100%;
		height: 100%;
		position: fixed;

		}

		.nav{
		display: list-item;
		margin:0px;
		font-style: none;
		color: #0C0B0C;
		}

		.col-md{
			font-weight: bold;
		font-size: 18px;
		padding: 40px 40px;
		}

		.pieDePagina{
		bottom: 0;
		padding: 4px;
		text-align: center;
		float:left; 
		width:100%;
		height: 10%;
		position:fixed;
		}

		.facebook{
		bottom: 5px;
		float: left;
		width: 40px;
		margin: 2px;
		display: inline-block;
		}

		.botonPaypal{
		position: fixed;
		bottom: 20px;
		right: 20px;
		}
		}

</style>
<img src="<%= asset_path 'imagenes/burguerMenu.png' %>" class="burguerMenu">
<header id="burguerMenu">
<nav class="fondo">
<ul class="no-list row center-xs middle-xs nav">
								<li class="col-md nav title">

								</li>

<% if user_signed_in? %>
		<li class="col-md">
		<%= link_to "Antes de comprar", extra_index_path, class:"link" %>
		</li>					
		<li class="col-md">
		<%= link_to "Ver mis programas", results_path, class:"link" %>
		</li>
		<li class="col-md">
		<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"link" %>
		</li>
				<li class="col-md">
				</li>

<%= link_to new_result_path do %>
<img class="botonPaypal" src="<%= asset_path 'slideimg/comprar.png' %>">
<%end%>

<%else%>
	<li class="col-md">
	<%= link_to "Obten tu programa", new_user_session_path, class:"link" %>
	</li>
	<li class="col-md">
	<%= link_to "Iniciar sesión", new_user_session_path, class:"link" %>
	</li>
	<li class="col-md">
	<%= link_to "Crear cuenta", new_user_registration_path, class:"link" %>
	</li>	
<%end%>
</ul>
</nav>
</header>

<div class="logoWinfittMovil">
<%= link_to root_path do %>
<img style="width:300px;" src="<%= asset_path 'anuncios/super logo.png' %>">
<% end %>	
</div>

<footer class="pieDePagina">
<img class="facebook" src="<%= asset_path 'anuncios/hecho en mexico.png' %>">
<a href="https://www.facebook.com/WinfittSoftware/" target="blank"><img class="facebook" src="<%= asset_path 'anuncios/anunciate.png' %>"></a>
</footer>

<script type="text/javascript">
	    $(".burguerMenu").click(function(){
        $("#burguerMenu").toggle(1000);
    });
</script>

app/views/partials/ventas.html.erb
<h1>
	aqui van las instrucciones de compra
</h1>

app/views/results/_aform.html.erb
<%= render "alimentacion/menu1" %>

app/views/results/_bitacora.html.erb
<h1>
    Aqui va el resultado de bitacora
</h1>

app/views/results/_cform.html.erb
<%= render "cardio/cardio1" %>

app/views/results/_eform.html.erb
<%= render "entrenamiento/zdpn1" %>

app/views/results/_mform.html.erb
<%= render "macrociclo/zzmhda10" %>

app/views/results/_resultados.html.erb
<div class="resultNav">
<input type="button" value="Macrociclo" class="btnM botonR">
<input type="button" value="Entrenamiento" class="btnE botonR">
<input type="button" value="Complementos" class="btnS botonR">
<input type="button" value="Cardiovascular" class="btnC botonR">
<input type="button" value="Alimentación" class="btnA botonR">
<input type="button" value="Bitacora" class="btnB botonR">       
</div>

<div class="scrollR">
<div class="resultados" id="receptor1">
<%= render "mform" %>
</div>

<div class="resultados" id="receptor2">
<%= render "eform" %>   
</div>

<div class="resultados" id="receptor3">
<%= render "sform" %>
</div>

<div class="resultados" id="receptor4">
<%= render "cform" %>
</div>

<div class="resultados" id="receptor5">
<%= render "aform" %>
</div>

<div class="resultadosB" id="receptor6">
<%= render "bitacora" %>
</div>    
</div>

<script type="text/javascript">
$(document).ready(function(){
    $(".btnM").click(function(){
        $("#receptor1").toggle(1500);
        $("#receptor2").hide();
        $("#receptor3").hide();
        $("#receptor4").hide();
        $("#receptor5").hide();
        $("#receptor6").hide();        
    });
});


$(document).ready(function(){
    $(".btnE").click(function(){
        $("#receptor2").toggle(1500);
        $("#receptor1").hide();
        $("#receptor3").hide();
        $("#receptor4").hide();
        $("#receptor5").hide();
        $("#receptor6").hide();  
    });
});

$(document).ready(function(){
        /*PARA TRAER EL RESULTADO DE CARDIOVASCULAR*/
        $(".btnS").click(function(){
        $("#receptor3").toggle(1500);
        $("#receptor1").hide();
        $("#receptor2").hide();
        $("#receptor4").hide();
        $("#receptor5").hide();
        $("#receptor6").hide();  
    });
});

$(document).ready(function(){
        /*PARA TRAER EL RESULTADO DE CARDIOVASCULAR*/
        $(".btnC").click(function(){
        $("#receptor4").toggle(1500);
        $("#receptor1").hide();
        $("#receptor2").hide();
        $("#receptor3").hide();
        $("#receptor5").hide();
        $("#receptor6").hide();  
    });
});

$(document).ready(function(){
        /*PARA TRAER EL RESULTADO DE ALIMENTACION*/
        $(".btnA").click(function(){
        $("#receptor5").toggle(1500);
        $("#receptor1").hide();
        $("#receptor2").hide();
        $("#receptor3").hide();
        $("#receptor4").hide();
        $("#receptor6").hide();  
    });
});

$(document).ready(function(){
    /*PARA TRAER EL RESULTADO DE ENTRENAMIENTO*/
        $(".btnB").click(function(){
        $("#receptor6").toggle(1500);
        $("#receptor1").hide();
        $("#receptor2").hide();
        $("#receptor3").hide();
        $("#receptor4").hide();
        $("#receptor5").hide();  
    });
});    
</script>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

app/views/results/_sform.html.erb
<%= render "complementos/comple1a" %>

app/views/results/index.html.erb
<div class="row center-xs">
		<h2 class="titulos"><%= current_user.email%> estos son tus programas:</h2>
</div>

<div class="scrollR">
	<% @results.each do |result| %>
	<div class="programas">
	<%= link_to "Programa con objetivo:", result, class:"link" %><%= result.objetivo%> ------------------------------------------- 
	<%= link_to "Eliminar", result, method: :delete, class:"linkEliminar" %>
	</div>
	<%end%>		
</div>

app/views/results/new.html.erb
<div class="titulos" id="sexos">
<h2>Aquí comienza el primer paso para alcanzar tu meta</h2>  
</div>

    <div class="resultForm">

    <h1>AQUÍ ME GUSTARIA INCLUIR LA PASARELA DE PAGO</h1>

        <% @result.errors.full_messages.each do |message| %>
        *<%= message %>
        <%end%> 

<%= form_for @result do |m| %>

<h2>Selecciona tu sexo:</h2>  
<%= m.radio_button :sexo, 1, :class => "rubyFields"%> 
<%= m.label(:sexo, "masculino") %>
<%= m.radio_button :sexo, 2, :class => "rubyFields"%>
<%= m.label(:sexo, "femenino") %>

<img class="rubyFields grasas" src="<%= asset_path 'menus/grasahombres.png' %>">
<h2>Selecciona tu porcentaje de grasa:</h2>
<%= m.radio_button(:grasa, 90, :class => "rubyFields")%>
<%= m.label(:grasa, "31-29")%>
<%= m.radio_button(:grasa, 80, :class => "rubyFields")%>
<%= m.label(:grasa, "28-26")%>
<%= m.radio_button(:grasa, 70, :class => "rubyFields")%>
<%= m.label(:grasa, "26-24")%>
<%= m.radio_button(:grasa, 60, :class => "rubyFields")%>
<%= m.label(:grasa, "23-21")%>
<%= m.radio_button(:grasa, 50, :class => "rubyFields")%>
<%= m.label(:grasa, "20-18")%>
<%= m.radio_button(:grasa, 40, :class => "rubyFields")%>
<%= m.label(:grasa, "17-15")%>
<%= m.radio_button(:grasa, 30, :class => "rubyFields")%>
<%= m.label(:grasa, "14-12")%>
<%= m.radio_button(:grasa, 20, :class => "rubyFields")%>
<%= m.label(:grasa, "11-9")%>   
<%= m.radio_button(:grasa, 10, :class => "rubyFields")%>        
<%= m.label(:grasa, "8-6")%>

<img class="rubyFields grasas" src="<%= asset_path 'menus/grasamujeres.png' %>">
<h2>Selecciona tu porcentaje de grasa:</h2>
<%= m.radio_button(:grasa, 9, :class => "rubyFields")%>
<%= m.label(:grasa, "42-40")%>
<%= m.radio_button(:grasa, 8, :class => "rubyFields")%>
<%= m.label(:grasa, "39-37")%>
<%= m.radio_button(:grasa, 7, :class => "rubyFields")%>
<%= m.label(:grasa, "36-34")%>
<%= m.radio_button(:grasa, 6, :class => "rubyFields")%>
<%= m.label(:grasa, "33-31")%>
<%= m.radio_button(:grasa, 5, :class => "rubyFields")%>
<%= m.label(:grasa, "30-28")%>
<%= m.radio_button(:grasa, 4, :class => "rubyFields")%>
<%= m.label(:grasa, "27-25")%>
<%= m.radio_button(:grasa, 3, :class => "rubyFields")%>
<%= m.label(:grasa, "24-22")%>
<%= m.radio_button(:grasa, 2, :class => "rubyFields")%>
<%= m.label(:grasa, "21-19")%>  
<%= m.radio_button(:grasa, 1, :class => "rubyFields")%>     
<%= m.label(:grasa, "18-16")%> 

<h2>Meses que llevas entrenando</h2>
<%= m.radio_button(:meses, 1, :class => "rubyFields") %>
<%= m.label(:meses, "principiante(De 0 a 15 días)") %>
<%= m.radio_button(:meses, 2, :class => "rubyFields") %>
<%= m.label(:meses, "intermedio(De 3 a 12 meses)") %>
<%= m.radio_button(:meses, 3, :class => "rubyFields") %>
<%= m.label(:meses, "avanzado(De 12 meses en adelante)") %>

<h2>Objetivo, tipo de entrenamiento</h2>
<%= m.radio_button(:objetivo, 1, :class => "rubyFields") %>
<%= m.label(:objetivo, "Definición") %>
<%= m.radio_button(:objetivo, 2, :class => "rubyFields") %>
<%= m.label(:objetivo, "Ganancia Muscular") %>
<%= m.radio_button(:objetivo, 3, :class => "rubyFields") %>
<%= m.label(:objetivo, "Resistencia") %>
<%= m.radio_button(:objetivo, 4, :class => "rubyFields") %>
<%= m.label(:objetivo, "Fuerza Máxima") %>

<h2>Selecciona el nivel de entrenamiento para ser mas especificos:</h2>

<%= m.radio_button(:nivel, 1, :class => "rubyFields")%>
<%= m.label(:nivel, "1(nunca he entrenado)")%>
<%= m.radio_button(:nivel, 2, :class => "rubyFields")%>
<%= m.label(:nivel, "2(tengo mas de medio año sin entrenar)")%>
<%= m.radio_button(:nivel, 3, :class => "rubyFields")%>
<%= m.label(:nivel, "3(tengo 15 días de entrenamiento)")%>
<%= m.radio_button(:nivel, 4, :class => "rubyFields")%>
<%= m.label(:nivel, "4(tengo 1 mes de entrenamiento)")%>
<%= m.radio_button(:nivel, 5, :class => "rubyFields")%>
<%= m.label(:nivel, "5(tengo 3 meses de entrenamiento)")%>
<%= m.radio_button(:nivel, 6, :class => "rubyFields")%>
<%= m.label(:nivel, "6(tengo 6 meses de entrenamiento)")%>

<h1>Alimentación</h1>

<h2>Selecciona el ritmo de entrenamiento en tu semana</h2>

<%= m.radio_button(:ritmo, 1.2, :class => "rubyFields")%>
<%= m.label(:ritmo, "Sedentario(solo entreno una vez por semana)")%>
<%= m.radio_button(:ritmo, 1.375, :class => "rubyFields")%>
<%= m.label(:ritmo, "Algo activo(entreno de 2 a 3 veces por semana)")%>
<%= m.radio_button(:ritmo, 1.55, :class => "rubyFields")%>
<%= m.label(:ritmo, "Activo(entreno 5 días a la semana)")%>
<%= m.radio_button(:ritmo, 1.725, :class => "rubyFields")%>
<%= m.label(:ritmo, "Muy activo(entreno todos los días de la semana)")%>
<%= m.radio_button(:ritmo, 1.9, :class => "rubyFields")%>
<%= m.label(:ritmo, "Extra activo(entreno todos los días de la semana, en ocaciones 2 veces al día)")%>

<h2>Selecciona tu meta en este mes</h2>

<%= m.radio_button(:meta, -500, :class => "rubyFields")%>
<%= m.label(:meta, "Definición al limite(recomendado despues de pasar 3 periodos con winfitt)")%>
<%= m.radio_button(:meta, -250, :class => "rubyFields")%>
<%= m.label(:meta, "Definición moderado(ideal si vas a comenzar tu primera definicion)")%>
<%= m.radio_button(:meta, 0, :class => "rubyFields")%>
<%= m.label(:meta, "Mentenimiento(ideal si vas a comenzar)")%>
<%= m.radio_button(:meta, 250, :class => "rubyFields")%>
<%= m.label(:meta, "Ganancia muscular moderado(ideal si vas a comenzar tu primera fase de volumen)")%>
<%= m.radio_button(:meta, 500, :class => "rubyFields")%>
<%= m.label(:meta, "Ganancia muscular al limite(recomendado despues de pasar 3 periodos con winfitt)")%>

<h2>Selecciona tu menú alimenticio en este mes</h2>

<label><%= m.radio_button(:menu, 1, :class => "radiob")%>
<img src="<%= asset_path 'menus/menu1.png'%>" class="menus">
</label>

<label><%= m.radio_button(:menu, 2, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu2.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 3, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu3.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 4, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu4.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 5, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu5.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 6, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu6.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 7, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu7.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 8, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu8.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 9, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu9.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 10, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu10.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 11, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu11.png'%>" class="menus">
</label> 

<label><%= m.radio_button(:menu, 12, :class => "radiob")%> 
<img src="<%= asset_path'menus/menu12.png'%>"  class="menus">
</label> 


<h2>Pon tu peso en kilos</h2>
<%= m.number_field(:kilos, in: 30.00..150.00, :class => "rubyFields") %>
<%= m.label("Peso en kilos")%>

<h2>Pon tu grasa corporal</h2>

<%= m.number_field(:egrasa, in: 8.00..45.00, :class => "rubyFields") %>
<%= m.label("porcentaje de grasa")%>


<h2>Pon tu edad</h2>

<%= m.number_field(:edad, in: 18.0..100.0, :class => "rubyFields") %>
<%= m.label(:edad, "Edad")%>


<h2>Pon tu frecuencia cardiaca en reposo</h2>

<%= m.number_field(:fmin, in: 10.0..200.0, :class => "rubyFields") %>
<%= m.label(:fmin, "Frecuencia cardiaca en reposo")%>


<h2>Estado en el que te encuentras en cuanto a condición fisica</h2>
<%= m.radio_button :cestado, 1, :class => "rubyFields" %>
<%= m.label(:cestado, "Principiante(tienes de 0 a 3 meses de entrenamiento)") %>
<%= m.radio_button :cestado, 2, :class => "rubyFields" %>
<%= m.label(:cestado, "Intermedio(tienes de 3 a 12 meses de entrenamiento)") %>
<%= m.radio_button :cestado, 3, :class => "rubyFields" %>
<%= m.label(:cestado, "Avanzado(tienes mas de 1 año entrenando constantemente)") %>

<h2>Escoge un nivel</h2>
<%= m.radio_button :cnivel, 1, :class => "rubyFields" %>
<%= m.label(:cnivel, "Uno(nunca he entrenado)") %>
<%= m.radio_button :cnivel, 2, :class => "rubyFields" %>
<%= m.label(:cnivel, "Dos(tengo 15 días entrenando)") %>
<%= m.radio_button :cnivel, 3, :class => "rubyFields" %>
<%= m.label(:cnivel, "Tres(tengo 3 meses de entrenamiento)") %>
<%= m.radio_button :cnivel, 4, :class => "rubyFields" %>
<%= m.label(:cnivel, "Cuatro(tengo 6 meses de entrenamiento)") %>
<%= m.radio_button :cnivel, 5, :class => "rubyFields" %>
<%= m.label(:cnivel, "Cinco(ya he pasado por el nivel anterior)") %>
<%= m.radio_button :cnivel, 6, :class => "rubyFields" %>
<%= m.label(:cnivel, "Seis(ya he pasado por el nivel anterior)") %>

<%= m.submit "Guardar Resultados", :class => "btnEnv rubyFieldsSubmit " %>
<% end %>
</div>

app/views/results/show.html.erb
<div>
<%= render 'resultados' %>		
</div>
<br>
<br>